# Generated by Django 5.1 on 2024-08-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoreparacion',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de Reparación'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=60, verbose_name='Nombre Completo'),
        ),
    ]
