# Generated by Django 5.1 on 2024-08-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehiculos', '0002_alter_autoreparacion_precio_venta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autoreparacion',
            old_name='precio_venta',
            new_name='precio_reparacion',
        ),
        migrations.AlterField(
            model_name='auto',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('VENDIDO', 'Fue Vendido'), ('REPARACION', 'En Mantenimiento')], default='DISPONIBLE', max_length=15, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='autoreparacion',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADO', 'Completado')], default='PENDIENTE', max_length=15, verbose_name='Estado'),
        ),
    ]
