# Generated by Django 5.1 on 2024-08-23 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehiculos', '0003_rename_precio_venta_autoreparacion_precio_reparacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('VENDIDO', 'Vendido'), ('REPARACION', 'En Mantenimiento')], default='DISPONIBLE', max_length=15, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='identidad',
            field=models.CharField(max_length=15, unique=True, verbose_name='Identidad'),
        ),
    ]
